Add RADAI to Data Tools section of README.md
CNERG/ETI.data_manual pull request #1
Opened 2022-01-07 19:29 UTC by thjoshi

An entry for RADAI has been added to the README.md. 

This includes a link to the repository and a description of of the library.

2022-01-07 19:51 UTC, jccurtis commented on README.md
> +3/ "[RADAI](https://gitlab.com/lbl-anp/radai/radai) (Radiological Anomaly Detection And
```suggestion
3. "[RADAI](https://gitlab.com/lbl-anp/radai/radai) (Radiological Anomaly Detection And
```

2022-01-12 15:55 UTC, stompsjo requested changes
Barring a rebase I think this looks great, thanks for the addition!

2022-01-12 15:55 UTC, stompsjo commented on README.md
> +3/ "[RADAI](https://gitlab.com/lbl-anp/radai/radai) (Radiological Anomaly Detection And
```suggestion
1. "[RADAI](https://gitlab.com/lbl-anp/radai/radai) (Radiological Anomaly Detection And
```

We can leave it at 1. and let Markdown order it for us.

2022-01-21 21:00 UTC, stompsjo approved these changes
I took the liberty of editing and rebasing. LGTM! Thanks for the addition!

2022-01-21 21:00 UTC, merged