Adding Limbo package to manual data streams
CNERG/ETI.data_manual pull request #3
Opened 2022-04-04 20:21 UTC by stompsjo

This PR includes information pertaining to [Limbo](https://limbo-ml.readthedocs.io/en/latest/index.html), a package and dataset for computer vision imagery. Thank you to @mbmcgarry for bringing this to our attention!

(I'll ping @tshead2, who is contributing to Limbo's repository, but feel free to add feedback or ping whoever is maintaining Limbo.)

2022-04-09 17:25 UTC, gonuke requested changes
I am not sure this dataset has been categorized properly in the table??

2022-04-09 17:25 UTC, gonuke commented on README.md
> +|[Limbo](#limbo)                                  |               |       x       |               |               |               |               |               |               |               |
did you mean to categorize this as `biota`?

2022-04-11 15:56 UTC, tshead2 commented on README.md
> +|[Limbo](#limbo)                                  |               |       x       |               |               |               |               |               |               |               |
I'm unfamiliar with this repo, but I'm the maintainer of Limbo and happy to answer questions.

Limbo definitely isn't biota :)  Looking at your categories, I'd go with imaging, and I'd add a new category for depth/LIDAR ... or include those in your definition of hyper spectral.

Cheers,
Tim

2022-04-11 19:07 UTC, stompsjo commented on README.md
> +|[Limbo](#limbo)                                  |               |       x       |               |               |               |               |               |               |               |
Thanks for the feedback! I apparently can't count columns...

This is corrected/included!

2022-04-11 19:43 UTC, gonuke approved these changes

2022-04-11 19:43 UTC, merged